const fs = require('fs');
const path = require('path');

function expandHome(value) {
  if (!value) return value;
  if (value === '~') return process.env.HOME;
  if (value.startsWith('~/')) return path.join(process.env.HOME || '', value.slice(2));
  return value;
}

function getCommandName(platform = process.platform) {
  return platform === 'win32' ? 'nightowl.cmd' : 'nightowl';
}

function candidateDirs(options = {}) {
  const home = options.home || process.env.HOME || '';
  return [
    options.targetDir,
    process.env.NIGHTOWL_CLI_DIR,
    '/usr/local/bin',
    path.join(home, '.local', 'bin')
  ].filter(Boolean).map(expandHome);
}

function isWritableDirectory(dir) {
  try {
    fs.mkdirSync(dir, { recursive: true });
    fs.accessSync(dir, fs.constants.W_OK);
    return true;
  } catch (_) {
    return false;
  }
}

function resolveTargetDir(options = {}) {
  for (const dir of candidateDirs(options)) {
    if (isWritableDirectory(dir)) return dir;
  }
  throw new Error('No writable CLI install directory found. Set NIGHTOWL_CLI_DIR to a writable directory.');
}

function pathIncludes(dir, envPath = process.env.PATH || '') {
  const resolvedDir = path.resolve(dir);
  return String(envPath)
    .split(path.delimiter)
    .filter(Boolean)
    .map(entry => path.resolve(entry))
    .includes(resolvedDir);
}

function escapeShell(value) {
  return String(value || '').replace(/'/g, `'\\''`);
}

function makeUnixShim({ appName = 'NightOwl', appPath = '', launcherPath = '' } = {}) {
  const appNameLiteral = escapeShell(appName);
  const appPathLiteral = escapeShell(appPath);
  const launcherPathLiteral = escapeShell(launcherPath);

  return `#!/usr/bin/env bash
# NightOwl CLI shim. Generated by NightOwl.
set -euo pipefail

APP_NAME='${appNameLiteral}'
APP_PATH='${appPathLiteral}'
LOCAL_LAUNCHER='${launcherPathLiteral}'

resolve_arg() {
  local arg="$1"
  if [[ "$arg" == -- || "$arg" == -* ]]; then
    printf '%s\\n' "$arg"
    return
  fi
  if [[ "$arg" == /* ]]; then
    printf '%s\\n' "$arg"
    return
  fi
  local dir
  dir="$(dirname "$arg")"
  local base
  base="$(basename "$arg")"
  if [[ -d "$dir" ]]; then
    printf '%s/%s\\n' "$(cd "$dir" && pwd -P)" "$base"
  else
    printf '%s\\n' "$arg"
  fi
}

args=()
for arg in "$@"; do
  args+=("$(resolve_arg "$arg")")
done

workspace_profile_args=()

append_workspace_profile_args() {
  local has_user_data=0
  local expect_user_data_value=0
  local first_path=''
  local arg
  for arg in "\${args[@]}"; do
    if [[ "$expect_user_data_value" == "1" ]]; then
      expect_user_data_value=0
      continue
    fi
    case "$arg" in
      --nightowl-user-data-dir|--user-data-dir)
        has_user_data=1
        expect_user_data_value=1
        ;;
      --nightowl-user-data-dir=*|--user-data-dir=*)
        has_user_data=1
        ;;
      --|--*|-*)
        ;;
      *)
        if [[ -z "$first_path" ]]; then
          first_path="$arg"
        fi
        ;;
    esac
  done

  if [[ "$has_user_data" == "1" || -z "$first_path" ]]; then
    return
  fi

  local workspace="$first_path"
  if [[ -f "$workspace" ]]; then
    workspace="$(dirname "$workspace")"
  elif [[ ! -d "$workspace" && "$workspace" == *.* ]]; then
    workspace="$(dirname "$workspace")"
  fi
  if [[ -d "$workspace" ]]; then
    workspace="$(cd "$workspace" && pwd -P)"
  fi

  local base_name
  base_name="$(basename "$workspace" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9._-]+/-/g; s/^-+//; s/-+$//' | cut -c1-48)"
  if [[ -z "$base_name" ]]; then
    base_name='workspace'
  fi

  local hash
  hash="$(printf '%s' "$workspace" | shasum | awk '{print substr($1, 1, 12)}')"

  local base_user_data
  if [[ "$(uname -s)" == "Darwin" ]]; then
    base_user_data="\${NIGHTOWL_USER_DATA_DIR:-$HOME/Library/Application Support/NightOwl}"
  else
    base_user_data="\${NIGHTOWL_USER_DATA_DIR:-\${XDG_CONFIG_HOME:-$HOME/.config}/NightOwl}"
  fi

  local workspace_user_data="$base_user_data/workspace-profiles/$base_name-$hash"
  workspace_profile_args=("--user-data-dir=$workspace_user_data" "--nightowl-user-data-dir=$workspace_user_data")
  export NIGHTOWL_WORKSPACE_USER_DATA_DIR="$workspace_user_data"
}

append_workspace_profile_args

if [[ -n "$LOCAL_LAUNCHER" && -f "$LOCAL_LAUNCHER" ]]; then
  export NIGHTOWL_CLI_DEV=1
  exec node "$LOCAL_LAUNCHER" "\${args[@]}"
fi

if [[ "$(uname -s)" == "Darwin" ]]; then
  if [[ -n "\${NIGHTOWL_APP_PATH:-}" ]]; then
    if [[ -d "\${NIGHTOWL_APP_PATH}" && -x "\${NIGHTOWL_APP_PATH}/Contents/MacOS/$APP_NAME" ]]; then
      exec "\${NIGHTOWL_APP_PATH}/Contents/MacOS/$APP_NAME" "\${workspace_profile_args[@]}" "\${args[@]}"
    fi
    exec open -n "\${NIGHTOWL_APP_PATH}" --args "\${workspace_profile_args[@]}" "\${args[@]}"
  fi
  if [[ -n "$APP_PATH" && -d "$APP_PATH" ]]; then
    if [[ -x "$APP_PATH/Contents/MacOS/$APP_NAME" ]]; then
      exec "$APP_PATH/Contents/MacOS/$APP_NAME" "\${workspace_profile_args[@]}" "\${args[@]}"
    fi
    exec open -n "$APP_PATH" --args "\${workspace_profile_args[@]}" "\${args[@]}"
  fi
  exec open -n -a "$APP_NAME" --args "\${workspace_profile_args[@]}" "\${args[@]}"
fi

if [[ -n "\${NIGHTOWL_APP_PATH:-}" && -x "\${NIGHTOWL_APP_PATH}" ]]; then
  exec "\${NIGHTOWL_APP_PATH}" "\${args[@]}"
fi
if [[ -n "$APP_PATH" && -x "$APP_PATH" ]]; then
  exec "$APP_PATH" "\${args[@]}"
fi

echo "nightowl: could not locate $APP_NAME. Set NIGHTOWL_APP_PATH to the app executable." >&2
exit 1
`;
}

function makeWindowsShim({ appName = 'NightOwl', appPath = '', launcherPath = '' } = {}) {
  if (launcherPath) {
    return `@echo off\r\nrem NightOwl CLI shim. Generated by NightOwl.\r\nset NIGHTOWL_CLI_DEV=1\r\nnode "${launcherPath.replace(/"/g, '""')}" %*\r\n`;
  }
  if (appPath) {
    return `@echo off\r\nrem NightOwl CLI shim. Generated by NightOwl.\r\nstart "" "${appPath.replace(/"/g, '""')}" %*\r\n`;
  }
  return `@echo off\r\nrem NightOwl CLI shim. Generated by NightOwl.\r\nstart "" "${appName.replace(/"/g, '""')}" %*\r\n`;
}

function isManagedNightOwlSymlink(target) {
  if (!fs.existsSync(target)) return false;
  const stat = fs.lstatSync(target);
  if (!stat.isSymbolicLink()) return false;
  try {
    return fs.realpathSync(target).endsWith(`${path.sep}bin${path.sep}nightowl`);
  } catch (_) {
    return false;
  }
}

function isManagedNightOwlFile(target) {
  try {
    if (!fs.existsSync(target) || !fs.lstatSync(target).isFile()) return false;
    const prefix = fs.readFileSync(target, 'utf8').slice(0, 256);
    return prefix.includes('NightOwl CLI shim. Generated by NightOwl.');
  } catch (_) {
    return false;
  }
}

function removeExisting(target, { force = false } = {}) {
  if (!fs.existsSync(target)) return false;
  const stat = fs.lstatSync(target);
  if (stat.isSymbolicLink() && (force || isManagedNightOwlSymlink(target))) {
    fs.unlinkSync(target);
    return true;
  }
  if (isManagedNightOwlFile(target)) {
    fs.unlinkSync(target);
    return true;
  }
  if (force) {
    fs.rmSync(target, { recursive: true, force: true });
    return true;
  }
  throw new Error(`${target} already exists. Re-run with --force or remove it first.`);
}

function installNightOwlCli(options = {}) {
  const targetDir = resolveTargetDir(options);
  const commandName = options.commandName || getCommandName(options.platform);
  const target = path.join(targetDir, commandName);

  removeExisting(target, { force: options.force === true });

  const shim = (options.platform || process.platform) === 'win32'
    ? makeWindowsShim(options)
    : makeUnixShim(options);

  fs.writeFileSync(target, shim, { mode: 0o755 });

  return {
    target,
    targetDir,
    commandName,
    pathIncludesTargetDir: pathIncludes(targetDir, options.envPath),
    replaced: false
  };
}

function uninstallNightOwlCli(options = {}) {
  const targetDir = resolveTargetDir(options);
  const commandName = options.commandName || getCommandName(options.platform);
  const target = path.join(targetDir, commandName);
  const removed = removeExisting(target, { force: options.force === true });
  return { target, targetDir, commandName, removed };
}

module.exports = {
  candidateDirs,
  expandHome,
  getCommandName,
  installNightOwlCli,
  makeUnixShim,
  makeWindowsShim,
  pathIncludes,
  removeExisting,
  resolveTargetDir,
  uninstallNightOwlCli
};
