const fs = require('fs');
const path = require('path');

function expandHome(value) {
  if (!value) return value;
  if (value === '~') return process.env.HOME;
  if (value.startsWith('~/')) return path.join(process.env.HOME || '', value.slice(2));
  return value;
}

function getCommandName(platform = process.platform) {
  return platform === 'win32' ? 'nightowl.cmd' : 'nightowl';
}

function candidateDirs(options = {}) {
  const home = options.home || process.env.HOME || '';
  return [
    options.targetDir,
    process.env.NIGHTOWL_CLI_DIR,
    '/usr/local/bin',
    path.join(home, '.local', 'bin')
  ].filter(Boolean).map(expandHome);
}

function isWritableDirectory(dir) {
  try {
    fs.mkdirSync(dir, { recursive: true });
    fs.accessSync(dir, fs.constants.W_OK);
    return true;
  } catch (_) {
    return false;
  }
}

function resolveTargetDir(options = {}) {
  for (const dir of candidateDirs(options)) {
    if (isWritableDirectory(dir)) return dir;
  }
  throw new Error('No writable CLI install directory found. Set NIGHTOWL_CLI_DIR to a writable directory.');
}

function pathIncludes(dir, envPath = process.env.PATH || '') {
  const resolvedDir = path.resolve(dir);
  return String(envPath)
    .split(path.delimiter)
    .filter(Boolean)
    .map(entry => path.resolve(entry))
    .includes(resolvedDir);
}

function escapeShell(value) {
  return String(value || '').replace(/'/g, `'\\''`);
}

function makeUnixShim({ appName = 'NightOwl', appPath = '', launcherPath = '' } = {}) {
  const appNameLiteral = escapeShell(appName);
  const appPathLiteral = escapeShell(appPath);
  const launcherPathLiteral = escapeShell(launcherPath);

  return `#!/usr/bin/env bash
# NightOwl CLI shim. Generated by NightOwl.
set -euo pipefail

APP_NAME='${appNameLiteral}'
APP_PATH='${appPathLiteral}'
LOCAL_LAUNCHER='${launcherPathLiteral}'

resolve_arg() {
  local arg="$1"
  if [[ "$arg" == -- || "$arg" == -* ]]; then
    printf '%s\\n' "$arg"
    return
  fi
  if [[ "$arg" == /* ]]; then
    printf '%s\\n' "$arg"
    return
  fi
  local dir
  dir="$(dirname "$arg")"
  local base
  base="$(basename "$arg")"
  if [[ -d "$dir" ]]; then
    printf '%s/%s\\n' "$(cd "$dir" && pwd -P)" "$base"
  else
    printf '%s\\n' "$arg"
  fi
}

args=()
for arg in "$@"; do
  args+=("$(resolve_arg "$arg")")
done

if [[ -n "$LOCAL_LAUNCHER" && -f "$LOCAL_LAUNCHER" ]]; then
  exec node "$LOCAL_LAUNCHER" "\${args[@]}"
fi

if [[ "$(uname -s)" == "Darwin" ]]; then
  if [[ -n "\${NIGHTOWL_APP_PATH:-}" ]]; then
    exec open "\${NIGHTOWL_APP_PATH}" --args "\${args[@]}"
  fi
  if [[ -n "$APP_PATH" && -d "$APP_PATH" ]]; then
    exec open "$APP_PATH" --args "\${args[@]}"
  fi
  exec open -a "$APP_NAME" --args "\${args[@]}"
fi

if [[ -n "\${NIGHTOWL_APP_PATH:-}" && -x "\${NIGHTOWL_APP_PATH}" ]]; then
  exec "\${NIGHTOWL_APP_PATH}" "\${args[@]}"
fi
if [[ -n "$APP_PATH" && -x "$APP_PATH" ]]; then
  exec "$APP_PATH" "\${args[@]}"
fi

echo "nightowl: could not locate $APP_NAME. Set NIGHTOWL_APP_PATH to the app executable." >&2
exit 1
`;
}

function makeWindowsShim({ appName = 'NightOwl', appPath = '', launcherPath = '' } = {}) {
  if (launcherPath) {
    return `@echo off\r\nrem NightOwl CLI shim. Generated by NightOwl.\r\nnode "${launcherPath.replace(/"/g, '""')}" %*\r\n`;
  }
  if (appPath) {
    return `@echo off\r\nrem NightOwl CLI shim. Generated by NightOwl.\r\nstart "" "${appPath.replace(/"/g, '""')}" %*\r\n`;
  }
  return `@echo off\r\nrem NightOwl CLI shim. Generated by NightOwl.\r\nstart "" "${appName.replace(/"/g, '""')}" %*\r\n`;
}

function isManagedNightOwlSymlink(target) {
  if (!fs.existsSync(target)) return false;
  const stat = fs.lstatSync(target);
  if (!stat.isSymbolicLink()) return false;
  try {
    return fs.realpathSync(target).endsWith(`${path.sep}bin${path.sep}nightowl`);
  } catch (_) {
    return false;
  }
}

function isManagedNightOwlFile(target) {
  try {
    if (!fs.existsSync(target) || !fs.lstatSync(target).isFile()) return false;
    const prefix = fs.readFileSync(target, 'utf8').slice(0, 256);
    return prefix.includes('NightOwl CLI shim. Generated by NightOwl.');
  } catch (_) {
    return false;
  }
}

function removeExisting(target, { force = false } = {}) {
  if (!fs.existsSync(target)) return false;
  const stat = fs.lstatSync(target);
  if (stat.isSymbolicLink() && (force || isManagedNightOwlSymlink(target))) {
    fs.unlinkSync(target);
    return true;
  }
  if (isManagedNightOwlFile(target)) {
    fs.unlinkSync(target);
    return true;
  }
  if (force) {
    fs.rmSync(target, { recursive: true, force: true });
    return true;
  }
  throw new Error(`${target} already exists. Re-run with --force or remove it first.`);
}

function installNightOwlCli(options = {}) {
  const targetDir = resolveTargetDir(options);
  const commandName = options.commandName || getCommandName(options.platform);
  const target = path.join(targetDir, commandName);

  removeExisting(target, { force: options.force === true });

  const shim = (options.platform || process.platform) === 'win32'
    ? makeWindowsShim(options)
    : makeUnixShim(options);

  fs.writeFileSync(target, shim, { mode: 0o755 });

  return {
    target,
    targetDir,
    commandName,
    pathIncludesTargetDir: pathIncludes(targetDir, options.envPath),
    replaced: false
  };
}

function uninstallNightOwlCli(options = {}) {
  const targetDir = resolveTargetDir(options);
  const commandName = options.commandName || getCommandName(options.platform);
  const target = path.join(targetDir, commandName);
  const removed = removeExisting(target, { force: options.force === true });
  return { target, targetDir, commandName, removed };
}

module.exports = {
  candidateDirs,
  expandHome,
  getCommandName,
  installNightOwlCli,
  makeUnixShim,
  makeWindowsShim,
  pathIncludes,
  removeExisting,
  resolveTargetDir,
  uninstallNightOwlCli
};
