const fs = require('fs');
const os = require('os');
const path = require('path');

const {
  installNightOwlCli,
  makeWindowsShim,
  makeUnixShim,
  pathIncludes
} = require('../../../services/cliInstaller');

describe('NightOwl CLI installer', () => {
  test('writes a managed shim that delegates to the local launcher when available', () => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'nightowl-cli-install-'));
    const launcherPath = path.join(tempDir, 'launcher.js');
    fs.writeFileSync(launcherPath, '#!/usr/bin/env node\n');

    const result = installNightOwlCli({
      targetDir: tempDir,
      launcherPath,
      envPath: tempDir
    });

    const installed = fs.readFileSync(result.target, 'utf8');
    expect(result.target).toBe(path.join(tempDir, 'nightowl'));
    expect(result.pathIncludesTargetDir).toBe(true);
    expect(installed).toContain('NightOwl CLI shim. Generated by NightOwl.');
    expect(installed).toContain(`LOCAL_LAUNCHER='${launcherPath}'`);
    expect(installed).toContain('export NIGHTOWL_CLI_DEV=1');
    expect(installed).toContain('exec node "$LOCAL_LAUNCHER"');
  });

  test('marks local launcher shims as dev launches on Windows', () => {
    const shim = makeWindowsShim({
      launcherPath: 'C:\\NightOwl\\bin\\nightowl'
    });

    expect(shim).toContain('set NIGHTOWL_CLI_DEV=1');
    expect(shim).toContain('node "C:\\NightOwl\\bin\\nightowl" %*');
  });

  test('reinstalls over a managed shim without force', () => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'nightowl-cli-install-'));

    installNightOwlCli({
      targetDir: tempDir,
      appPath: '/Applications/NightOwl.app',
      envPath: ''
    });
    const result = installNightOwlCli({
      targetDir: tempDir,
      appPath: '/Applications/NightOwl.app',
      envPath: ''
    });

    expect(fs.existsSync(result.target)).toBe(true);
    expect(result.pathIncludesTargetDir).toBe(false);
  });

  test('standalone macOS shim launches app bundles with workspace profiles', () => {
    const shim = makeUnixShim({
      appName: 'NightOwl',
      appPath: '/Applications/NightOwl.app'
    });

    expect(shim).toContain('append_workspace_profile_args');
    expect(shim).toContain('--nightowl-user-data-dir');
    expect(shim).toContain('workspace-profiles');
    expect(shim).toContain('exec "$APP_PATH/Contents/MacOS/$APP_NAME"');
    expect(shim).toContain('open -n -a "$APP_NAME" --args');
    expect(shim).toContain('resolve_arg');
  });

  test('pathIncludes checks normalized PATH entries', () => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'nightowl-path-'));
    expect(pathIncludes(tempDir, `/tmp${path.delimiter}${tempDir}`)).toBe(true);
    expect(pathIncludes(tempDir, '/tmp')).toBe(false);
  });
});
